using UnityEngine;

public enum EventType
{
    [InspectorName(null)]
    NULL,
    PLAYER_DIED,
    MOVEMENT_TOWARDS_TARGET_DONE,
    ENEMY_IN_RANGE,
    OBJECT_NOW_IN_RANGE,
    OBJECT_OUT_OF_RANGE,
    LEVER_OPENING,
    BACKPACK_OPEN_CLOSE_EVENT,
    INTERACTION_DONE,
    GATE_OPENED,
    LEVER_OPENED,
    CHARACTER_LEVEL_UP,
    QUEST_ACCEPTED,
    QUEST_REJECTED,
    QUEST_STEP_COMPLETED,
    NPC_QUEST_AVAILABLE,
    QUEST_CONFIRMATION_NEEDED,
    OBJECT_DESTROYED,
    PLAYER_TALKING_TO_NPC,
    NPC_DIED,
    RESET_HEALTH,
    QUEST_RETRY,
    NPC_REACHED_POINT,
    ENEMY_KILLED,
    PLAYER_COLLIDED,
    GROUND_DETECTED,
    STARTED_FALLING,
    CHECKPOINT_ENTERED
}
