using UnityEditor;
using UnityEngine;

public enum EventType
{
    PLAYER_DIED,
    ENEMY_IN_RANGE,
    OBJECT_NOW_IN_RANGE,
    OBJECT_OUT_OF_RANGE,
    LEVER_OPENING,
    LEVER_OPENED,
    GATE_OPENED,
    BACKPACK_OPEN_CLOSE_EVENT,
    INTERACTION_DONE
}
